In [15]:
import numpy as np

arr = np.arange(1,9)

In [16]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
lista = [1,2,3,4,5,6,7,8]

In [18]:
arr.shape = (2,4)
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
arr + arr #Adiction

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [20]:
lista + lista

[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]

In [21]:
arr - arr #sustraccion

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
arr * arr #producto

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [23]:
arr ** arr #exponenciacion 

array([[       1,        4,       27,      256],
       [    3125,    46656,   823543, 16777216]], dtype=int32)

In [14]:
arr/arr #division 

array([1., 1., 1., 1., 1., 1., 1., 1.])