In [21]:
import numpy as np

arr = np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
arr_flot = np.random.rand(4,3)
arr_flot

array([[0.40620976, 0.07439757, 0.65123888],
       [0.09984636, 0.82704904, 0.91378146],
       [0.63639648, 0.2261897 , 0.64399863],
       [0.45272141, 0.61651451, 0.84424274]])

In [23]:
arr_ent = np.random.randint(10, size=(2,3))
arr_ent

array([[3, 8, 6],
       [4, 3, 7]])

In [24]:
arr_6 = np.full((3,3), 6)
arr_6

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [25]:
np.append(arr, [12,13, 14, 51])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 12, 13, 14, 51])

In [26]:
np.insert(arr,2, [42,34])

array([ 0,  2, 42, 34,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
np.insert(arr_6,2, [1,2,4])

array([6, 6, 1, 2, 4, 6, 6, 6, 6, 6, 6, 6])

In [27]:
np.delete(arr_ent,1,axis=0)

array([[3, 8, 6]])

In [32]:
np.delete(arr_ent,0,axis=0)

array([[4, 3, 7]])

In [33]:
np.delete(arr_ent,1,axis=1)

array([[3, 6],
       [4, 7]])

In [34]:
np.delete(arr_ent,0,axis=1)

array([[8, 6],
       [3, 7]])