In [24]:
import numpy as np 

arr_ent = np.random.randint(100, size=(3,4))
arr_ent

array([[19, 21, 46, 84],
       [94, 12, 86, 50],
       [78, 84, 46,  5]])

In [25]:
arr_ent.astype(float)

array([[19., 21., 46., 84.],
       [94., 12., 86., 50.],
       [78., 84., 46.,  5.]])

In [26]:
arr_ent

array([[19, 21, 46, 84],
       [94, 12, 86, 50],
       [78, 84, 46,  5]])

In [27]:
arr_ent.sort()
arr_ent

array([[19, 21, 46, 84],
       [12, 50, 86, 94],
       [ 5, 46, 78, 84]])

In [28]:
arr_ent.sort(axis=0)
arr_ent

array([[ 5, 21, 46, 84],
       [12, 46, 78, 84],
       [19, 50, 86, 94]])

In [29]:
arr_ent 

array([[ 5, 21, 46, 84],
       [12, 46, 78, 84],
       [19, 50, 86, 94]])

In [31]:
arr_ent = arr_ent.reshape(4,3)
arr_ent

array([[ 5, 21, 46],
       [84, 12, 46],
       [78, 84, 19],
       [50, 86, 94]])

In [9]:
plano_arr = arr_ent.flatten()

print(arr_ent)
print(plano_arr)

[[ 9 10]
 [21 74]
 [16 20]
 [32 85]
 [49 83]
 [83 92]]
[ 9 10 21 74 16 20 32 85 49 83 83 92]


In [10]:
lista_arr = plano_arr.tolist()
lista_arr

[9, 10, 21, 74, 16, 20, 32, 85, 49, 83, 83, 92]

In [15]:
lista_arr = plano_arr.tolist()
lista_arr
type(lista_arr)

list

In [32]:
arrays= np.split(arr_ent, 4)
arrays

[array([[ 5, 21, 46]]),
 array([[84, 12, 46]]),
 array([[78, 84, 19]]),
 array([[50, 86, 94]])]

In [35]:
np.concatenate((arrays[1],arrays[0]), axis=1)

array([[84, 12, 46,  5, 21, 46]])

In [36]:
arr_ent

array([[ 5, 21, 46],
       [84, 12, 46],
       [78, 84, 19],
       [50, 86, 94]])

In [37]:
t_arr = arr_ent.T
t_arr

array([[ 5, 84, 78, 50],
       [21, 12, 84, 86],
       [46, 46, 19, 94]])