In [1]:
import numpy as np

a = np.array(range(64)).reshape((8,8))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [2]:
a[1,1]

9

In [5]:
a[0:7:2,0:4]

array([[ 0,  1,  2,  3],
       [16, 17, 18, 19],
       [32, 33, 34, 35],
       [48, 49, 50, 51]])

In [6]:
a[1,3:5]

array([11, 12])

In [7]:
a[[1,3,5],[3,6,7]]

array([11, 30, 47])

In [8]:
a[[1,3,5],::3]

array([[ 8, 11, 14],
       [24, 27, 30],
       [40, 43, 46]])

In [9]:
data = np.arange(8)
data

array([0, 1, 2, 3, 4, 5, 6, 7])

In [10]:
data <4

array([ True,  True,  True,  True, False, False, False, False])

In [11]:
data[data < 4]

array([0, 1, 2, 3])

In [12]:
data[np.array([ True, True, True, True, False, False, False, False])]

array([0, 1, 2, 3])

In [13]:
amigos = np.array(['giulia', 'victor', 'johel', 'andreina', 'valentina', 'albert', 'roque'])

In [14]:
'giulia' in amigos

True

In [15]:
amigos[amigos=='giulia']

array(['giulia'], dtype='<U9')